### ISSUE TITLE
unable to generate `google.ai.generativelanguage.v1`

### ISSUE THREAD

**Issue by devoncarew** [googleapis/google-cloud-rust#1598]
I'm encountering an issue when trying to generate `google.ai.generativelanguage.v1`. My sidekick.toml file is:

```toml
[general]
specification-source = 'google/ai/generativelanguage/v1'
service-config = 'google/ai/generativelanguage/v1/generativelanguage_v1.yaml'
```

And the issue I'm seeing is:

```
error refreshing directory generated/google_cloud_generativelanguage:
  cannot find output type .google.protobuf.Empty for method .google.ai.generativelanguage.v1.ModelService.CancelOperation
```

This is from api/xref.go, `CrossReference()` - before the backends get a chance to run. I've tried to debug but wasn't able to make progress. It is interesting that it's not able to resolve `.google.protobuf.Empty`.

I don't believe that `generativelanguage` is one of the API we generally intend to generate, but it would be useful to me - it is one of the APIs that allows using an api key, and, there is a hand-written Dart implementation of it that we could compare w/ the generated output.
